//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS.Mefx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VS.Mefx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing all the rejection issues.
        /// </summary>
        internal static string AllRejectionsMessage {
            get {
                return ResourceManager.GetString("AllRejectionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string AllText {
            get {
                return ResourceManager.GetString("AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Considering exporting field {0}.
        /// </summary>
        internal static string ConsideringExportFormat {
            get {
                return ResourceManager.GetString("ConsideringExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing matching for importing field {0}.
        /// </summary>
        internal static string ConsideringImportFormat {
            get {
                return ResourceManager.GetString("ConsideringImportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Contract Name - {0}].
        /// </summary>
        internal static string ContractNameFormat {
            get {
                return ResourceManager.GetString("ContractNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered following errors when finding parts:.
        /// </summary>
        internal static string DiscoveryErrors {
            get {
                return ResourceManager.GetString("DiscoveryErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught following error: {0}.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors in level {0}.
        /// </summary>
        internal static string ErrorsLevelMessage {
            get {
                return ResourceManager.GetString("ErrorsLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: {0}, Found: {1}.
        /// </summary>
        internal static string ExpectedFoundFormat {
            get {
                return ResourceManager.GetString("ExpectedFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Export] Field: {0}, Contract Name: {1}.
        /// </summary>
        internal static string ExportDetailFormat {
            get {
                return ResourceManager.GetString("ExportDetailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting parts for {0}:.
        /// </summary>
        internal static string ExportingContractsFormat {
            get {
                return ResourceManager.GetString("ExportingContractsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export matches all import constraints.
        /// </summary>
        internal static string ExportMatchingImport {
            get {
                return ResourceManager.GetString("ExportMatchingImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Constraint #{0}.
        /// </summary>
        internal static string FailedConstraintIdentifer {
            get {
                return ResourceManager.GetString("FailedConstraintIdentifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any potential matches between the two given parts.
        /// </summary>
        internal static string FoundNoMatchesText {
            get {
                return ResourceManager.GetString("FoundNoMatchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Import] Field: {0}, Contract Name: {1}.
        /// </summary>
        internal static string ImportDetailFormat {
            get {
                return ResourceManager.GetString("ImportDetailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing parts for {0}:.
        /// </summary>
        internal static string ImportingContractsFormat {
            get {
                return ResourceManager.GetString("ImportingContractsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Rejection Graph Info for {0}.
        /// </summary>
        internal static string IndividualRejectionMessage {
            get {
                return ResourceManager.GetString("IndividualRejectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name of {0}.
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find matches from {0} to {1}.
        /// </summary>
        internal static string MatchingPartsFormat {
            get {
                return ResourceManager.GetString("MatchingPartsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide exactly two parts to the match option.
        /// </summary>
        internal static string MatchRequiresTwoMessage {
            get {
                return ResourceManager.GetString("MatchRequiresTwoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Metadata - Key: {0}, Value: {1}].
        /// </summary>
        internal static string MetadataFormat {
            get {
                return ResourceManager.GetString("MetadataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the following exporting fields:.
        /// </summary>
        internal static string MissingExportMessage {
            get {
                return ResourceManager.GetString("MissingExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find file {0}.
        /// </summary>
        internal static string MissingFileMessage {
            get {
                return ResourceManager.GetString("MissingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find directory {0}.
        /// </summary>
        internal static string MissingFolderMessage {
            get {
                return ResourceManager.GetString("MissingFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the following importing fields:.
        /// </summary>
        internal static string MissingImportMessage {
            get {
                return ResourceManager.GetString("MissingImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such key.
        /// </summary>
        internal static string MissingKeyText {
            get {
                return ResourceManager.GetString("MissingKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find part with name {0}.
        /// </summary>
        internal static string MissingPartFormat {
            get {
                return ResourceManager.GetString("MissingPartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find directory {0} so saving rejection graph to current directory.
        /// </summary>
        internal static string MissingRelativePath {
            get {
                return ResourceManager.GetString("MissingRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any parts in the input files and folders.
        /// </summary>
        internal static string NoPartsMessage {
            get {
                return ResourceManager.GetString("NoPartsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rejection Issues associated with {0}.
        /// </summary>
        internal static string NoRejectionMessage {
            get {
                return ResourceManager.GetString("NoRejectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string NullText {
            get {
                return ResourceManager.GetString("NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing out details for part {0}.
        /// </summary>
        internal static string PartDetailFormat {
            get {
                return ResourceManager.GetString("PartDetailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts in the Catalog are .
        /// </summary>
        internal static string PartsDescription {
            get {
                return ResourceManager.GetString("PartsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved cache of current catalog to {0}.
        /// </summary>
        internal static string SavedCacheMessage {
            get {
                return ResourceManager.GetString("SavedCacheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved rejection graph to {0}.
        /// </summary>
        internal static string SavedGraphMessage {
            get {
                return ResourceManager.GetString("SavedGraphMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Type - {0}].
        /// </summary>
        internal static string TypeFormat {
            get {
                return ResourceManager.GetString("TypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Part].
        /// </summary>
        internal static string VerbosePartLabel {
            get {
                return ResourceManager.GetString("VerbosePartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Whitelisted] .
        /// </summary>
        internal static string WhitelistLabel {
            get {
                return ResourceManager.GetString("WhitelistLabel", resourceCulture);
            }
        }
    }
}
