//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Composition {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Composition.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All values must be non-null..
        /// </summary>
        internal static string AllValuesMustBeNonNull {
            get {
                return ResourceManager.GetString("AllValuesMustBeNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyName must be set first..
        /// </summary>
        internal static string AssemblyNameMustBeSetFirst {
            get {
                return ResourceManager.GetString("AssemblyNameMustBeSetFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty..
        /// </summary>
        internal static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is an import and cannot be directly disposed..
        /// </summary>
        internal static string CannotDirectlyDisposeAnImport {
            get {
                return ResourceManager.GetString("CannotDirectlyDisposeAnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: cannot import exported value from {1} because the exporting part cannot be instantiated. Is it missing an importing constructor?.
        /// </summary>
        internal static string CannotImportBecauseExportingPartCannotBeInstantiated {
            get {
                return ResourceManager.GetString("CannotImportBecauseExportingPartCannotBeInstantiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection must be public with a public constructor when used with an [ImportingConstructor]..
        /// </summary>
        internal static string CollectionMustBePublicAndPublicCtorWhenUsingImportingCtor {
            get {
                return ResourceManager.GetString("CollectionMustBePublicAndPublicCtorWhenUsingImportingCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection type must derive from ICollection&lt;T&gt;..
        /// </summary>
        internal static string CollectionTypeMustDeriveFromICollectionOfT {
            get {
                return ResourceManager.GetString("CollectionTypeMustDeriveFromICollectionOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation errors occurred..
        /// </summary>
        internal static string CompilerErrorsOccurred {
            get {
                return ResourceManager.GetString("CompilerErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantiated part(s) threw exception(s) from IDisposable.Dispose()..
        /// </summary>
        internal static string ContainerDisposalEncounteredExceptions {
            get {
                return ResourceManager.GetString("ContainerDisposalEncounteredExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom import sources are not yet supported..
        /// </summary>
        internal static string CustomImportSourceNotSupported {
            get {
                return ResourceManager.GetString("CustomImportSourceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &quot;{0}&quot; contains metadata attributes with an identical property name. Property name: &quot;{1}&quot;..
        /// </summary>
        internal static string DiscoveredIdenticalPropertiesInMetadataAttributesForPart {
            get {
                return ResourceManager.GetString("DiscoveredIdenticalPropertiesInMetadataAttributesForPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred during discovery..
        /// </summary>
        internal static string ErrorsDuringDiscovery {
            get {
                return ResourceManager.GetString("ErrorsDuringDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors exist in the composition..
        /// </summary>
        internal static string ErrorsInComposition {
            get {
                return ResourceManager.GetString("ErrorsInComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &quot;{0}&quot; could not be satisfied..
        /// </summary>
        internal static string ErrorWhileSettingImport {
            get {
                return ResourceManager.GetString("ErrorWhileSettingImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be exactly one entry for every import..
        /// </summary>
        internal static string ExactlyOneEntryForEveryImport {
            get {
                return ResourceManager.GetString("ExactlyOneEntryForEveryImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown while initializing part &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionThrownByPartUnderInitialization {
            get {
                return ResourceManager.GetString("ExceptionThrownByPartUnderInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: expected exactly 1 export of {1} but found {2}.{3}.
        /// </summary>
        internal static string ExpectedExactlyOneExportButFound {
            get {
                return ResourceManager.GetString("ExpectedExactlyOneExportButFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: expected 1 or 0 exports of {1} but found {2}.{3}.
        /// </summary>
        internal static string ExpectedOneOrZeroExportsButFound {
            get {
                return ResourceManager.GetString("ExpectedOneOrZeroExportsButFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value exported from &quot;{0}&quot; cannot be assigned to import site &quot;{1}&quot;..
        /// </summary>
        internal static string ExportedValueNotAssignableToImport {
            get {
                return ResourceManager.GetString("ExportedValueNotAssignableToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Export of ExportProvider is not allowed..
        /// </summary>
        internal static string ExportOfExportProviderNotAllowed {
            get {
                return ResourceManager.GetString("ExportOfExportProviderNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports on members not allowed when the declaring type is generic..
        /// </summary>
        internal static string ExportsOnMembersNotAllowedWhenDeclaringTypeGeneric {
            get {
                return ResourceManager.GetString("ExportsOnMembersNotAllowedWhenDeclaringTypeGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate embeddable types..
        /// </summary>
        internal static string FailedToGenerateEmbeddableTypes {
            get {
                return ResourceManager.GetString("FailedToGenerateEmbeddableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a stable composition..
        /// </summary>
        internal static string FailStableComposition {
            get {
                return ResourceManager.GetString("FailStableComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure while scanning type &quot;{0}&quot;..
        /// </summary>
        internal static string FailureWhileScanningType {
            get {
                return ResourceManager.GetString("FailureWhileScanningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import constraint type {0} is not supported..
        /// </summary>
        internal static string ImportConstraintTypeNotSupported {
            get {
                return ResourceManager.GetString("ImportConstraintTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing constructor has an unsupported parameter type for an [ImportMany]. Only T[] and IEnumerable&lt;T&gt; are supported..
        /// </summary>
        internal static string ImportingCtorHasUnsupportedParameterTypeForImportMany {
            get {
                return ResourceManager.GetString("ImportingCtorHasUnsupportedParameterTypeForImportMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: imports that use generic type parameters are not supported..
        /// </summary>
        internal static string ImportsThatUseGenericTypeParametersNotSupported {
            get {
                return ResourceManager.GetString("ImportsThatUseGenericTypeParametersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is empty..
        /// </summary>
        internal static string InstanceEmpty {
            get {
                return ResourceManager.GetString("InstanceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is expected only on imports of ExportFactory&lt;T&gt;..
        /// </summary>
        internal static string IsExpectedOnlyOnImportsOfExportFactoryOfT {
            get {
                return ResourceManager.GetString("IsExpectedOnlyOnImportsOfExportFactoryOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsExportFactory is expected to be true..
        /// </summary>
        internal static string IsExportFactoryExpectedTrue {
            get {
                return ResourceManager.GetString("IsExportFactoryExpectedTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: is not assignable from exported MEF value {1}..
        /// </summary>
        internal static string IsNotAssignableFromExportedMEFValue {
            get {
                return ResourceManager.GetString("IsNotAssignableFromExportedMEFValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop between non-shared parts..
        /// </summary>
        internal static string LoopBetweenNonSharedParts {
            get {
                return ResourceManager.GetString("LoopBetweenNonSharedParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop involving ImportingConstructor argument and all non-lazy imports..
        /// </summary>
        internal static string LoopInvolvingImportingCtorArgumentAndAllNonLazyImports {
            get {
                return ResourceManager.GetString("LoopInvolvingImportingCtorArgumentAndAllNonLazyImports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &quot;{0}&quot; contains both ImportAttribute and ImportManyAttribute..
        /// </summary>
        internal static string MemberContainsBothImportAndImportMany {
            get {
                return ResourceManager.GetString("MemberContainsBothImportAndImportMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: metadata type {1} is not supported..
        /// </summary>
        internal static string MetadataTypeNotSupported {
            get {
                return ResourceManager.GetString("MetadataTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No importing constructor..
        /// </summary>
        internal static string NoImportingConstructor {
            get {
                return ResourceManager.GetString("NoImportingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No importing constructor found..
        /// </summary>
        internal static string NoImportingConstructorFound {
            get {
                return ResourceManager.GetString("NoImportingConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No member to satisfy..
        /// </summary>
        internal static string NoMemberToSatisfy {
            get {
                return ResourceManager.GetString("NoMemberToSatisfy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a type spec..
        /// </summary>
        internal static string NotATypeSpec {
            get {
                return ResourceManager.GetString("NotATypeSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a closed form of the other..
        /// </summary>
        internal static string NotClosedFormOfOther {
            get {
                return ResourceManager.GetString("NotClosedFormOfOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a generic type definition..
        /// </summary>
        internal static string NotGenericTypeDefinition {
            get {
                return ResourceManager.GetString("NotGenericTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not initialized..
        /// </summary>
        internal static string NotInitialized {
            get {
                return ResourceManager.GetString("NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnImportsSatisfied method should take no parameters..
        /// </summary>
        internal static string OnImportsSatisfiedTakeNoParameters {
            get {
                return ResourceManager.GetString("OnImportsSatisfiedTakeNoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one OnImportsSatisfied method is supported..
        /// </summary>
        internal static string OnlyOneOnImportsSatisfiedMethodIsSupported {
            get {
                return ResourceManager.GetString("OnlyOneOnImportsSatisfiedMethodIsSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supported on write operations..
        /// </summary>
        internal static string OnlySupportedOnWriteOperations {
            get {
                return ResourceManager.GetString("OnlySupportedOnWriteOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropriate request for export from part that belongs to another sharing boundary..
        /// </summary>
        internal static string PartBelongsToAnotherSharingBoundary {
            get {
                return ResourceManager.GetString("PartBelongsToAnotherSharingBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This part ({0}) cannot be instantiated..
        /// </summary>
        internal static string PartIsNotInstantiable {
            get {
                return ResourceManager.GetString("PartIsNotInstantiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part is not shared..
        /// </summary>
        internal static string PartIsNotShared {
            get {
                return ResourceManager.GetString("PartIsNotShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readable stream required..
        /// </summary>
        internal static string ReadableStreamRequired {
            get {
                return ResourceManager.GetString("ReadableStreamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to construct MEF part &quot;{0}&quot; due to an unresolvable recursive construction request..
        /// </summary>
        internal static string RecursiveRequestForPartConstruction {
            get {
                return ResourceManager.GetString("RecursiveRequestForPartConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectionTypeLoadException while enumerating types in assembly &quot;{0}&quot;. Results will be incomplete..
        /// </summary>
        internal static string ReflectionTypeLoadExceptionWhileEnumeratingTypes {
            get {
                return ResourceManager.GetString("ReflectionTypeLoadExceptionWhileEnumeratingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning MEF assemblies....
        /// </summary>
        internal static string ScanningMEFAssemblies {
            get {
                return ResourceManager.GetString("ScanningMEFAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} already belongs to the catalog as a different ComposablePartDefinition..
        /// </summary>
        internal static string TypeAlreadyInCatalogAsAnotherPart {
            get {
                return ResourceManager.GetString("TypeAlreadyInCatalogAsAnotherPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be the one that defines memberInfo or a derived type..
        /// </summary>
        internal static string TypeMustDefineMemberInfoOrDerivedType {
            get {
                return ResourceManager.GetString("TypeMustDefineMemberInfoOrDerivedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of metadata view is unsupported..
        /// </summary>
        internal static string TypeOfMetadataViewUnsupported {
            get {
                return ResourceManager.GetString("TypeOfMetadataViewUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the primary sharing boundary for MEF part &quot;{0}&quot;..
        /// </summary>
        internal static string UnableToDeterminePrimarySharingBoundary {
            get {
                return ResourceManager.GetString("UnableToDeterminePrimarySharingBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to enumerate types in assembly &quot;{0}&quot;..
        /// </summary>
        internal static string UnableToEnumerateTypes {
            get {
                return ResourceManager.GetString("UnableToEnumerateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to instantiate custom import collection type..
        /// </summary>
        internal static string UnableToInstantiateCustomImportCollectionType {
            get {
                return ResourceManager.GetString("UnableToInstantiateCustomImportCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load assembly &quot;{0}&quot; for scanning..
        /// </summary>
        internal static string UnableToLoadAssembly {
            get {
                return ResourceManager.GetString("UnableToLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected constraint type: {0}..
        /// </summary>
        internal static string UnexpectedConstraintType {
            get {
                return ResourceManager.GetString("UnexpectedConstraintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected member type {0}..
        /// </summary>
        internal static string UnexpectedMemberType {
            get {
                return ResourceManager.GetString("UnexpectedMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} export(s) with contract name &quot;{1}&quot; but found {2} after applying applicable constraints..
        /// </summary>
        internal static string UnexpectedNumberOfExportsFound {
            get {
                return ResourceManager.GetString("UnexpectedNumberOfExportsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shared part is in state {0} but must be in state {1} for this operation..
        /// </summary>
        internal static string UnexpectedSharedPartState {
            get {
                return ResourceManager.GetString("UnexpectedSharedPartState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolvable metadata token..
        /// </summary>
        internal static string UnresolvableMetadataToken {
            get {
                return ResourceManager.GetString("UnresolvableMetadataToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported format: {0}..
        /// </summary>
        internal static string UnsupportedFormat {
            get {
                return ResourceManager.GetString("UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writable stream required..
        /// </summary>
        internal static string WritableStreamRequired {
            get {
                return ResourceManager.GetString("WritableStreamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong length..
        /// </summary>
        internal static string WrongLength {
            get {
                return ResourceManager.GetString("WrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong type..
        /// </summary>
        internal static string WrongType {
            get {
                return ResourceManager.GetString("WrongType", resourceCulture);
            }
        }
    }
}
