//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Composition {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Composition.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is an import and cannot be directly disposed..
        /// </summary>
        internal static string CannotDirectlyDisposeAnImport {
            get {
                return ResourceManager.GetString("CannotDirectlyDisposeAnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantiated part(s) threw exception(s) from IDisposable.Dispose()..
        /// </summary>
        internal static string ContainerDisposalEncounteredExceptions {
            get {
                return ResourceManager.GetString("ContainerDisposalEncounteredExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred during discovery..
        /// </summary>
        internal static string ErrorsDuringDiscovery {
            get {
                return ResourceManager.GetString("ErrorsDuringDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors exist in the composition..
        /// </summary>
        internal static string ErrorsInComposition {
            get {
                return ResourceManager.GetString("ErrorsInComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &quot;{0}&quot; could not be satisfied..
        /// </summary>
        internal static string ErrorWhileSettingImport {
            get {
                return ResourceManager.GetString("ErrorWhileSettingImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown while initializing part &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionThrownByPartUnderInitialization {
            get {
                return ResourceManager.GetString("ExceptionThrownByPartUnderInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value exported from &quot;{0}&quot; cannot be assigned to import site &quot;{1}&quot;..
        /// </summary>
        internal static string ExportedValueNotAssignableToImport {
            get {
                return ResourceManager.GetString("ExportedValueNotAssignableToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a stable composition..
        /// </summary>
        internal static string FailStableComposition {
            get {
                return ResourceManager.GetString("FailStableComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure while scanning type &quot;{0}&quot;..
        /// </summary>
        internal static string FailureWhileScanningType {
            get {
                return ResourceManager.GetString("FailureWhileScanningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No importing constructor.
        /// </summary>
        internal static string NoImportingConstructor {
            get {
                return ResourceManager.GetString("NoImportingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropriate request for export from part that belongs to another sharing boundary..
        /// </summary>
        internal static string PartBelongsToAnotherSharingBoundary {
            get {
                return ResourceManager.GetString("PartBelongsToAnotherSharingBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This part ({0}) cannot be instantiated..
        /// </summary>
        internal static string PartIsNotInstantiable {
            get {
                return ResourceManager.GetString("PartIsNotInstantiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectionTypeLoadException while enumerating types in assembly &quot;{0}&quot;. Results will be incomplete..
        /// </summary>
        internal static string ReflectionTypeLoadExceptionWhileEnumeratingTypes {
            get {
                return ResourceManager.GetString("ReflectionTypeLoadExceptionWhileEnumeratingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning MEF assemblies....
        /// </summary>
        internal static string ScanningMEFAssemblies {
            get {
                return ResourceManager.GetString("ScanningMEFAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of metadata view is unsupported..
        /// </summary>
        internal static string TypeOfMetadataViewUnsupported {
            get {
                return ResourceManager.GetString("TypeOfMetadataViewUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the primary sharing boundary for MEF part &quot;{0}&quot;..
        /// </summary>
        internal static string UnableToDeterminePrimarySharingBoundary {
            get {
                return ResourceManager.GetString("UnableToDeterminePrimarySharingBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to enumerate types in assembly &quot;{0}&quot;..
        /// </summary>
        internal static string UnableToEnumerateTypes {
            get {
                return ResourceManager.GetString("UnableToEnumerateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to instantiate custom import collection type..
        /// </summary>
        internal static string UnableToInstantiateCustomImportCollectionType {
            get {
                return ResourceManager.GetString("UnableToInstantiateCustomImportCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load assembly &quot;{0}&quot; for scanning..
        /// </summary>
        internal static string UnableToLoadAssembly {
            get {
                return ResourceManager.GetString("UnableToLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected member type.
        /// </summary>
        internal static string UnexpectedMemberType {
            get {
                return ResourceManager.GetString("UnexpectedMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} export(s) with contract name &quot;{1}&quot; but found {2} after applying applicable constraints..
        /// </summary>
        internal static string UnexpectedNumberOfExportsFound {
            get {
                return ResourceManager.GetString("UnexpectedNumberOfExportsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shared part is in state {0} but must be in state {1} for this operation..
        /// </summary>
        internal static string UnexpectedSharedPartState {
            get {
                return ResourceManager.GetString("UnexpectedSharedPartState", resourceCulture);
            }
        }
    }
}
