// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Microsoft.VisualStudio.Composition.Analyzers.CSharp;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

/// <summary>
/// Generates <c>MetadataView</c> implementations for metadata view interfaces marked with <c>[MetadataView]</c>.
/// </summary>
[Generator]
public sealed class MetadataViewSourceGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeNameFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly SymbolDisplayFormat NonNullableTypeNameFormat = SymbolDisplayFormat.FullyQualifiedFormat;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<MetadataViewSpec> metadataViewSpecs = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                Types.MetadataViewAttribute.FullName,
                static (node, _) => node is InterfaceDeclarationSyntax,
                static (generatorContext, cancellationToken) => CreateMetadataViewSpec((INamedTypeSymbol)generatorContext.TargetSymbol, cancellationToken))
            .Where(static spec => spec.HasValue)
            .Select(static (spec, _) => spec.GetValueOrDefault());

        context.RegisterSourceOutput(metadataViewSpecs, static (productionContext, spec) =>
        {
            productionContext.AddSource(spec.HintName, GenerateSource(spec));
        });
    }

    private static MetadataViewSpec? CreateMetadataViewSpec(INamedTypeSymbol metadataViewInterface, CancellationToken cancellationToken)
    {
        if (metadataViewInterface.TypeKind != TypeKind.Interface
            || MetadataViewGeneratorUtilities.HasAttribute(metadataViewInterface, Types.MetadataViewImplementationAttribute.FullName)
            || !MetadataViewGeneratorUtilities.IsPartialInterfaceAndContainingTypes(metadataViewInterface, cancellationToken)
            || !MetadataViewGeneratorUtilities.IsGeneratableMetadataViewInterface(metadataViewInterface))
        {
            return null;
        }

        string generatedTypeName = GetGeneratedTypeName(metadataViewInterface);
        string interfaceNamespace = metadataViewInterface.ContainingNamespace is { IsGlobalNamespace: false } containingNamespace ? containingNamespace.ToDisplayString() : string.Empty;
        ImmutableArray<ContainingTypeSpec> containingTypes = GetContainingTypes(metadataViewInterface, cancellationToken);
        return new MetadataViewSpec(
            InterfaceMetadataName: metadataViewInterface.ToDisplayString(TypeNameFormat),
            InterfaceNamespace: interfaceNamespace,
            InterfaceDeclaration: GetPartialInterfaceDeclaration(metadataViewInterface, cancellationToken),
            ContainingTypes: containingTypes,
            GeneratedTypeName: generatedTypeName,
            GeneratedTypeTypeParameters: GetTypeParameterList(metadataViewInterface),
            GeneratedTypeConstraints: GetConstraintClauses(metadataViewInterface, cancellationToken),
            GeneratedTypeAttributeQualifiedName: GetQualifiedGeneratedTypeNameForAttribute(interfaceNamespace, containingTypes, generatedTypeName, metadataViewInterface.TypeParameters.Length),
            HintName: generatedTypeName + ".g.cs",
            Properties: GetMetadataProperties(metadataViewInterface)
                .Select(property => new MetadataPropertySpec(property.Name, property.Type.ToDisplayString(TypeNameFormat), GetDefaultValueAttributeSource(property, cancellationToken)))
                .ToImmutableArray());
    }

    private static Microsoft.CodeAnalysis.Text.SourceText GenerateSource(MetadataViewSpec metadataView)
    {
        string generatorVersion = ThisAssembly.AssemblyFileVersion;

        var writer = new SourceWriter(' ', 4);
        writer.WriteLine("// <auto-generated />", disableIndentation: true);
        writer.WriteLine("#nullable enable", disableIndentation: true);
        writer.WriteLine();

        if (!string.IsNullOrEmpty(metadataView.InterfaceNamespace))
        {
            writer.WriteLine($"namespace {metadataView.InterfaceNamespace}");
            writer.WriteLine("{");
            writer.Indentation++;
        }

        foreach (ContainingTypeSpec containingType in metadataView.ContainingTypes)
        {
            writer.WriteLine(containingType.Declaration);
            writer.WriteLine("{");
            writer.Indentation++;
        }

        writer.WriteLine($"[{Types.MetadataViewImplementationAttribute.QualifiedName}(typeof({metadataView.GeneratedTypeAttributeQualifiedName}))]");
        writer.WriteLine(metadataView.InterfaceDeclaration);
        writer.WriteLine("{");
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine($"[{Types.GeneratedCodeAttribute.QualifiedName}(\"{typeof(MetadataViewSourceGenerator).FullName}\", \"{generatorVersion}\")]");
        writer.WriteLine($"internal sealed class {metadataView.GeneratedTypeName}{metadataView.GeneratedTypeTypeParameters} : {Types.MetadataView.QualifiedName}, {metadataView.InterfaceMetadataName}{metadataView.GeneratedTypeConstraints}");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine($"public {metadataView.GeneratedTypeName}()");
        writer.WriteLine("{");
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine($"public {metadataView.GeneratedTypeName}(global::System.Collections.Generic.IDictionary<string, object> metadata)");
        writer.WriteLine(": base(metadata)");
        writer.WriteLine("{");
        writer.WriteLine("}");
        writer.WriteLine();
        foreach (MetadataPropertySpec property in metadataView.Properties)
        {
            if (property.DefaultValueAttributeSource is not null)
            {
                writer.WriteLine(property.DefaultValueAttributeSource);
            }

            writer.WriteLine($"public {property.TypeName} {property.Name} => this.GetMetadata<{property.TypeName}>();");
            writer.WriteLine();
        }

        writer.Indentation--;
        writer.WriteLine("}");

        for (int i = 0; i < metadataView.ContainingTypes.Length; i++)
        {
            writer.Indentation--;
            writer.WriteLine("}");
        }

        if (!string.IsNullOrEmpty(metadataView.InterfaceNamespace))
        {
            writer.Indentation--;
            writer.WriteLine("}");
        }

        return writer.ToSourceText();
    }

    private static string GetPartialInterfaceDeclaration(INamedTypeSymbol metadataViewInterface, CancellationToken cancellationToken)
    {
        InterfaceDeclarationSyntax declaration = metadataViewInterface.DeclaringSyntaxReferences
            .Select(reference => reference.GetSyntax(cancellationToken))
            .OfType<InterfaceDeclarationSyntax>()
            .First();
        string typeParameters = declaration.TypeParameterList?.ToFullString().TrimEnd() ?? string.Empty;
        string constraints = declaration.ConstraintClauses.Count > 0
            ? " " + string.Join(" ", declaration.ConstraintClauses.Select(static clause => clause.ToFullString().Trim()))
            : string.Empty;
        return $"partial interface {declaration.Identifier.Text}{typeParameters}{constraints}";
    }

    private static IEnumerable<IPropertySymbol> GetMetadataProperties(INamedTypeSymbol metadataViewInterface)
    {
        var seenNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (INamedTypeSymbol interfaceType in new[] { metadataViewInterface }.Concat(metadataViewInterface.AllInterfaces))
        {
            foreach (IPropertySymbol property in interfaceType.GetMembers().OfType<IPropertySymbol>())
            {
                if (property.IsIndexer || property.GetMethod is null || property.SetMethod is not null)
                {
                    continue;
                }

                if (seenNames.Add(property.Name))
                {
                    yield return property;
                }
            }
        }
    }

    private static string GetGeneratedTypeName(INamedTypeSymbol metadataViewInterface)
    {
        char[] sanitized = metadataViewInterface
            .ToDisplayString()
            .Select(ch => char.IsLetterOrDigit(ch) ? ch : '_')
            .ToArray();
        return "__VsMefMetadataView_" + new string(sanitized);
    }

    private static string GetConstraintClauses(INamedTypeSymbol metadataViewInterface, CancellationToken cancellationToken)
    {
        InterfaceDeclarationSyntax declaration = metadataViewInterface.DeclaringSyntaxReferences
            .Select(reference => reference.GetSyntax(cancellationToken))
            .OfType<InterfaceDeclarationSyntax>()
            .First();
        return declaration.ConstraintClauses.Count > 0
            ? string.Concat(" ", string.Join(" ", declaration.ConstraintClauses.Select(static clause => clause.ToFullString().Trim())))
            : string.Empty;
    }

    private static string GetQualifiedGeneratedTypeNameForAttribute(string interfaceNamespace, ImmutableArray<ContainingTypeSpec> containingTypes, string generatedTypeName, int genericArity)
    {
        var segments = new List<string>(containingTypes.Length + 1);
        segments.AddRange(containingTypes.Select(static containingType => containingType.AttributeTypeName));
        segments.Add(generatedTypeName + GetUnboundTypeParameterList(genericArity));
        return string.IsNullOrEmpty(interfaceNamespace)
            ? "global::" + string.Join(".", segments)
            : "global::" + interfaceNamespace + "." + string.Join(".", segments);
    }

    private static ImmutableArray<ContainingTypeSpec> GetContainingTypes(INamedTypeSymbol metadataViewInterface, CancellationToken cancellationToken)
    {
        var builder = ImmutableArray.CreateBuilder<ContainingTypeSpec>();
        for (INamedTypeSymbol? containingType = metadataViewInterface.ContainingType; containingType is not null; containingType = containingType.ContainingType)
        {
            builder.Add(CreateContainingTypeSpec(containingType, cancellationToken));
        }

        return builder.ToImmutable().Reverse().ToImmutableArray();
    }

    private static ContainingTypeSpec CreateContainingTypeSpec(INamedTypeSymbol containingType, CancellationToken cancellationToken)
    {
        TypeDeclarationSyntax declaration = containingType.DeclaringSyntaxReferences
            .Select(reference => reference.GetSyntax(cancellationToken))
            .OfType<TypeDeclarationSyntax>()
            .First();
        string typeParameters = declaration.TypeParameterList?.ToFullString().TrimEnd() ?? string.Empty;
        string constraints = declaration.ConstraintClauses.Count > 0
            ? " " + string.Join(" ", declaration.ConstraintClauses.Select(static clause => clause.ToFullString().Trim()))
            : string.Empty;

        string declarationHeader = declaration switch
        {
            RecordDeclarationSyntax recordDeclaration when recordDeclaration.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword) => "partial record struct " + declaration.Identifier.Text + typeParameters + constraints,
            RecordDeclarationSyntax => "partial record " + declaration.Identifier.Text + typeParameters + constraints,
            ClassDeclarationSyntax => "partial class " + declaration.Identifier.Text + typeParameters + constraints,
            StructDeclarationSyntax => "partial struct " + declaration.Identifier.Text + typeParameters + constraints,
            InterfaceDeclarationSyntax => "partial interface " + declaration.Identifier.Text + typeParameters + constraints,
            _ => throw new InvalidOperationException("Unsupported containing type declaration."),
        };

        return new ContainingTypeSpec(declarationHeader, containingType.Name + GetUnboundTypeParameterList(containingType.TypeParameters.Length));
    }

    private static string GetTypeParameterList(INamedTypeSymbol type)
    {
        return type.TypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", type.TypeParameters.Select(static parameter => parameter.Name)) + ">";
    }

    private static string GetUnboundTypeParameterList(int genericArity)
    {
        return genericArity == 0
            ? string.Empty
            : "<" + new string(',', genericArity - 1) + ">";
    }

    private static string? GetDefaultValueAttributeSource(IPropertySymbol property, CancellationToken cancellationToken)
    {
        AttributeData? defaultValueAttribute = property.GetAttributes()
            .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == Types.DefaultValueAttribute.FullName);
        if (defaultValueAttribute is not null)
        {
            string arguments = string.Join(
                ", ",
                defaultValueAttribute.ConstructorArguments.Select(GetAttributeArgumentSource)
                    .Concat(defaultValueAttribute.NamedArguments.Select(static arg => arg.Key + " = " + GetAttributeArgumentSource(arg.Value))));
            return $"[{Types.DefaultValueAttribute.QualifiedName}({arguments})]";
        }

        return null;
    }

    private static string GetAttributeArgumentSource(TypedConstant argument)
    {
        return argument.Kind switch
        {
            TypedConstantKind.Array => "new " + argument.Type!.ToDisplayString(NonNullableTypeNameFormat) + " { " + string.Join(", ", argument.Values.Select(GetAttributeArgumentSource)) + " }",
            TypedConstantKind.Enum => GetEnumArgumentSource(argument),
            TypedConstantKind.Type when argument.Value is ITypeSymbol typeSymbol => $"typeof({typeSymbol.ToDisplayString(NonNullableTypeNameFormat)})",
            _ => GetPrimitiveArgumentSource(argument),
        };
    }

    private static string GetEnumArgumentSource(TypedConstant argument)
    {
        var enumType = (INamedTypeSymbol)argument.Type!;
        IFieldSymbol? matchingField = enumType.GetMembers()
            .OfType<IFieldSymbol>()
            .FirstOrDefault(field => field.HasConstantValue && Equals(field.ConstantValue, argument.Value));
        if (matchingField is not null)
        {
            return enumType.ToDisplayString(NonNullableTypeNameFormat) + "." + matchingField.Name;
        }

        return "(" + enumType.ToDisplayString(NonNullableTypeNameFormat) + ")" + GetPrimitiveLiteral(enumType.EnumUnderlyingType!.SpecialType, argument.Value!);
    }

    private static string GetPrimitiveArgumentSource(TypedConstant argument)
    {
        if (argument.Value is null)
        {
            return "null";
        }

        return GetPrimitiveLiteral(argument.Type!.SpecialType, argument.Value);
    }

    private static string GetPrimitiveLiteral(SpecialType specialType, object value)
    {
        return specialType switch
        {
            SpecialType.System_Boolean => (bool)value ? "true" : "false",
            SpecialType.System_Byte => $"(byte){((byte)value).ToString(CultureInfo.InvariantCulture)}",
            SpecialType.System_SByte => $"(sbyte){((sbyte)value).ToString(CultureInfo.InvariantCulture)}",
            SpecialType.System_Int16 => $"(short){((short)value).ToString(CultureInfo.InvariantCulture)}",
            SpecialType.System_UInt16 => $"(ushort){((ushort)value).ToString(CultureInfo.InvariantCulture)}",
            SpecialType.System_Int32 => ((int)value).ToString(CultureInfo.InvariantCulture),
            SpecialType.System_UInt32 => ((uint)value).ToString(CultureInfo.InvariantCulture) + "U",
            SpecialType.System_Int64 => ((long)value).ToString(CultureInfo.InvariantCulture) + "L",
            SpecialType.System_UInt64 => ((ulong)value).ToString(CultureInfo.InvariantCulture) + "UL",
            SpecialType.System_Single => GetSingleLiteral((float)value),
            SpecialType.System_Double => GetDoubleLiteral((double)value),
            SpecialType.System_Decimal => ((decimal)value).ToString(CultureInfo.InvariantCulture) + "M",
            SpecialType.System_Char => SymbolDisplay.FormatLiteral((char)value, true),
            SpecialType.System_String => SymbolDisplay.FormatLiteral((string)value, true),
            _ => throw new InvalidOperationException("Unsupported DefaultValueAttribute argument type."),
        };
    }

    private static string GetSingleLiteral(float value)
    {
        return float.IsNaN(value)
            ? "global::System.Single.NaN"
            : float.IsPositiveInfinity(value)
            ? "global::System.Single.PositiveInfinity"
            : float.IsNegativeInfinity(value)
            ? "global::System.Single.NegativeInfinity"
            : value.ToString("R", CultureInfo.InvariantCulture) + "F";
    }

    private static string GetDoubleLiteral(double value)
    {
        return double.IsNaN(value)
            ? "global::System.Double.NaN"
            : double.IsPositiveInfinity(value)
            ? "global::System.Double.PositiveInfinity"
            : double.IsNegativeInfinity(value)
            ? "global::System.Double.NegativeInfinity"
            : value.ToString("R", CultureInfo.InvariantCulture) + "D";
    }

    private readonly record struct MetadataViewSpec(
        string InterfaceMetadataName,
        string InterfaceNamespace,
        string InterfaceDeclaration,
        ImmutableArray<ContainingTypeSpec> ContainingTypes,
        string GeneratedTypeName,
        string GeneratedTypeTypeParameters,
        string GeneratedTypeConstraints,
        string GeneratedTypeAttributeQualifiedName,
        string HintName,
        ImmutableArray<MetadataPropertySpec> Properties);

    private readonly record struct MetadataPropertySpec(string Name, string TypeName, string? DefaultValueAttributeSource);

    private readonly record struct ContainingTypeSpec(string Declaration, string AttributeTypeName);
}
