//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Composition {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Composition.ConfigurationStrings", typeof(ConfigurationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyName must be set first..
        /// </summary>
        internal static string AssemblyNameMustBeSetFirst {
            get {
                return ResourceManager.GetString("AssemblyNameMustBeSetFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty..
        /// </summary>
        internal static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection must be public with a public constructor when used with an [ImportingConstructor]..
        /// </summary>
        internal static string CollectionMustBePublicAndPublicCtorWhenUsingImportingCtor {
            get {
                return ResourceManager.GetString("CollectionMustBePublicAndPublicCtorWhenUsingImportingCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation errors occurred..
        /// </summary>
        internal static string CompilerErrorsOccurred {
            get {
                return ResourceManager.GetString("CompilerErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom import sources are not yet supported..
        /// </summary>
        internal static string CustomImportSourceNotSupported {
            get {
                return ResourceManager.GetString("CustomImportSourceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports on members not allowed when the declaring type is generic..
        /// </summary>
        internal static string ExportsOnMembersNotAllowedWhenDeclaringTypeGeneric {
            get {
                return ResourceManager.GetString("ExportsOnMembersNotAllowedWhenDeclaringTypeGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate embeddable types..
        /// </summary>
        internal static string FailedToGenerateEmbeddableTypes {
            get {
                return ResourceManager.GetString("FailedToGenerateEmbeddableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import constraint type {0} is not supported..
        /// </summary>
        internal static string ImportConstraintTypeNotSupported {
            get {
                return ResourceManager.GetString("ImportConstraintTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is expected only on imports of ExportFactory&lt;T&gt;..
        /// </summary>
        internal static string IsExpectedOnlyOnImportsOfExportFactoryOfT {
            get {
                return ResourceManager.GetString("IsExpectedOnlyOnImportsOfExportFactoryOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsExportFactory is expected to be true..
        /// </summary>
        internal static string IsExportFactoryExpectedTrue {
            get {
                return ResourceManager.GetString("IsExportFactoryExpectedTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &quot;{0}&quot; contains both ImportAttribute and ImportManyAttribute..
        /// </summary>
        internal static string MemberContainsBothImportAndImportMany {
            get {
                return ResourceManager.GetString("MemberContainsBothImportAndImportMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No importing constructor found..
        /// </summary>
        internal static string NoImportingConstructorFound {
            get {
                return ResourceManager.GetString("NoImportingConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No member to satisfy..
        /// </summary>
        internal static string NoMemberToSatisfy {
            get {
                return ResourceManager.GetString("NoMemberToSatisfy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnImportsSatisfied method should take no parameters..
        /// </summary>
        internal static string OnImportsSatisfiedTakeNoParameters {
            get {
                return ResourceManager.GetString("OnImportsSatisfiedTakeNoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one OnImportsSatisfied method is supported..
        /// </summary>
        internal static string OnlyOneOnImportsSatisfiedMethodIsSupported {
            get {
                return ResourceManager.GetString("OnlyOneOnImportsSatisfiedMethodIsSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supported on write operations..
        /// </summary>
        internal static string OnlySupportedOnWriteOperations {
            get {
                return ResourceManager.GetString("OnlySupportedOnWriteOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readable stream required..
        /// </summary>
        internal static string ReadableStreamRequired {
            get {
                return ResourceManager.GetString("ReadableStreamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be the one that defines memberInfo or a derived type..
        /// </summary>
        internal static string TypeMustDefineMemberInfoOrDerivedType {
            get {
                return ResourceManager.GetString("TypeMustDefineMemberInfoOrDerivedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected constraint type: {0}..
        /// </summary>
        internal static string UnexpectedConstraintType {
            get {
                return ResourceManager.GetString("UnexpectedConstraintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported format: {0}..
        /// </summary>
        internal static string UnsupportedFormat {
            get {
                return ResourceManager.GetString("UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writable stream required..
        /// </summary>
        internal static string WritableStreamRequired {
            get {
                return ResourceManager.GetString("WritableStreamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong type..
        /// </summary>
        internal static string WrongType {
            get {
                return ResourceManager.GetString("WrongType", resourceCulture);
            }
        }
    }
}
