//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Composition.Analyzers
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Composition.Analyzers.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A property with an [ImportAttribute] must define a setter so the export can be set on the property..
        /// </summary>
        internal static string VSMEF001_MessageFormat
        {
            get
            {
                return ResourceManager.GetString("VSMEF001_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Importing property must have setter.
        /// </summary>
        internal static string VSMEF001_Title
        {
            get
            {
                return ResourceManager.GetString("VSMEF001_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; contains a mix of attributes from MEFv1 and MEFv2. Consolidate to just one variety of attributes..
        /// </summary>
        internal static string VSMEF002_MessageFormat
        {
            get
            {
                return ResourceManager.GetString("VSMEF002_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Avoid mixing MEF attribute varieties.
        /// </summary>
        internal static string VSMEF002_Title
        {
            get
            {
                return ResourceManager.GetString("VSMEF002_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type "{0}" does not implement the exported type "{1}". This may be an authoring mistake..
        /// </summary>
        internal static string VSMEF003_MessageFormat
        {
            get
            {
                return ResourceManager.GetString("VSMEF003_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exported type not implemented by exporting class.
        /// </summary>
        internal static string VSMEF003_Title
        {
            get
            {
                return ResourceManager.GetString("VSMEF003_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; defines exports but has non-default constructors that are not annotated with [ImportingConstructor]. Add a parameterless constructor, or annotate a constructor with [ImportingConstructor]..
        /// </summary>
        internal static string VSMEF004_MessageFormat
        {
            get
            {
                return ResourceManager.GetString("VSMEF004_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exported type missing importing constructor.
        /// </summary>
        internal static string VSMEF004_Title
        {
            get
            {
                return ResourceManager.GetString("VSMEF004_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; has multiple constructors annotated with [ImportingConstructor]. Only one constructor should be marked as importing..
        /// </summary>
        internal static string VSMEF005_MessageFormat
        {
            get
            {
                return ResourceManager.GetString("VSMEF005_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple importing constructors.
        /// </summary>
        internal static string VSMEF005_Title
        {
            get
            {
                return ResourceManager.GetString("VSMEF005_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The import "{0}" has AllowDefault = true but is not nullable. Consider making the type nullable or removing AllowDefault..
        /// </summary>
        internal static string VSMEF006_AllowDefaultWithoutNullable_MessageFormat
        {
            get
            {
                return ResourceManager.GetString("VSMEF006_AllowDefaultWithoutNullable_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The import "{0}" is nullable but does not have AllowDefault = true. Consider adding AllowDefault = true or making the type non-nullable..
        /// </summary>
        internal static string VSMEF006_NullableWithoutAllowDefault_MessageFormat
        {
            get
            {
                return ResourceManager.GetString("VSMEF006_NullableWithoutAllowDefault_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import nullability and AllowDefault mismatch.
        /// </summary>
        internal static string VSMEF006_Title
        {
            get
            {
                return ResourceManager.GetString("VSMEF006_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type "{0}" imports the same contract "{1}" multiple times. Each contract should only be imported once per type..
        /// </summary>
        internal static string VSMEF007_MessageFormat
        {
            get
            {
                return ResourceManager.GetString("VSMEF007_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate import contract.
        /// </summary>
        internal static string VSMEF007_Title
        {
            get
            {
                return ResourceManager.GetString("VSMEF007_Title", resourceCulture);
            }
        }
    }
}
