trigger:
  branches:
    include: ["main", "v*"]
  paths:
    exclude: ["doc", "*.md"]
pr: none

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
  NugetSecurityAnalysisWarningLevel: none # we use packages.lock.json to verify package content.

jobs:
- job: Windows
  pool: VSEngSS-MicroBuild2019
  steps:
  - template: build.yml
